name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure project with CMake
        run: |
          cd Y22
          mkdir -p build
          cd build
          cmake ..

      - name: Build with Make
        run: |
          cd Y22/build
          make

      - name: Run tests (if using CTest)
        run: |
          cd Y22/src
          ctest --output-on-failure
