name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: |
          cd Y22
          find src tests \( -name '*.cpp' -o -name '*.h' \) | xargs cpplint --linelength=80

      - name: Configure project with CMake
        run: |
          cd Y22
          mkdir -p build
          cd build
          cmake ..

      - name: Build with Make
        run: |
          cd Y22/build
          make

      - name: Run tests with CTest
        run: |
          cd Y22/build
          ctest --output-on-failure
